import {DEFAULTS,inspectText,parseSignal,detectRPeaks,analyze,synthetic} from './engine.js';
const $=id=>document.getElementById(id);
const state={raw:{ecg:null,bp:null},ecg:null,bp:null,peaks:null,analysis:null,manual:new Set(),demo:false};
const qcSpec=[['rrMin','RR minimum','ms'],['rrMax','RR maximum','ms'],['rrDeviation','RR deviation','%'],['rSnr','R-peak amplitude limit','MAD'],['sbpMin','SBP minimum','mmHg'],['sbpMax','SBP maximum','mmHg'],['dbpMin','DBP minimum','mmHg'],['dbpMax','DBP maximum','mmHg'],['ppMin','PP minimum','mmHg'],['ppMax','PP maximum','mmHg'],['sbpDrift','SBP local deviation','mmHg'],['driftBeats','Local median window','beats'],['bpDelay','BP pulse delay','ms'],['brsSbpStep','BRS SBP step','mmHg'],['brsRrStep','BRS RR step','ms'],['brsMinR','BRS minimum r','']];
for(const [key,label,unit] of qcSpec){const e=document.createElement('label');e.textContent=label+(unit?` (${unit})`:'');const inp=document.createElement('input');inp.id=`qc_${key}`;inp.type='number';inp.step=key==='brsMinR'?'0.01':'any';inp.value=DEFAULTS[key];e.append(inp);$('qcFields').append(e);}
function settings(){const s={};for(const [key] of qcSpec){const v=Number($(`qc_${key}`).value);if(!Number.isFinite(v))throw Error(`Enter a valid ${key} threshold.`);s[key]=v;}if(s.rrMin>=s.rrMax||s.sbpMin>=s.sbpMax||s.dbpMin>=s.dbpMax||s.ppMin>=s.ppMax)throw Error('Each minimum must be below its maximum.');if(s.brsMinR<0||s.brsMinR>1)throw Error('BRS minimum r must be 0–1.');return s;}
function notice(message,error=false){$('notice').textContent=message;$('notice').classList.toggle('error',error);}
function optionsFor(kind,text){const meta=inspectText(text),v=$(kind+'Value'),t=$(kind+'Time');v.replaceChildren();t.replaceChildren();const none=document.createElement('option');none.value='-1';none.textContent='None · sample rate';t.append(none);meta.headers.forEach((h,i)=>{for(const select of [v,t]){const o=document.createElement('option');o.value=i;o.textContent=h;select.append(o);}});v.value=String(meta.headers.length>1?1:0);t.value=String(meta.headers.length>1?0:-1);return meta;}
for(const kind of ['ecg','bp']){$(kind+'File').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const text=await f.text();state.raw[kind]=text;state.demo=false;const meta=optionsFor(kind,text);$(kind+'Name').textContent=`${f.name} · ${meta.lineCount.toLocaleString()} lines`;notice(`${kind.toUpperCase()} loaded locally. Confirm the selected columns and sample rate.`);}catch(err){notice(err.message,true);}});}
$('windowMode').addEventListener('change',()=>{$('customFields').style.display=$('windowMode').value==='custom'?'grid':'none';});$('customFields').style.display='none';
$('demo').addEventListener('click',()=>{const s=synthetic();state.ecg=s.ecg;state.bp=s.bp;state.peaks=detectRPeaks(s.ecg);state.demo=true;state.manual.clear();$('ecgName').textContent='Synthetic ECG · 250 Hz';$('bpName').textContent='Synthetic BP · 250 Hz';$('windowMode').value='last';$('windowMinutes').value='5';$('customFields').style.display='none';$('bpOffset').value='0';notice('Synthetic 5½-minute example loaded. The final five minutes are selected.');run(true);});
$('run').addEventListener('click',()=>run(false));
function readUploads(){
  if(!state.raw.ecg||!state.raw.bp)throw Error('Choose both ECG and BP files, or try the synthetic example.');
  const parse=kind=>parseSignal(state.raw[kind],{fs:Number($(kind+'Fs').value),valueColumn:Number($(kind+'Value').value),timeColumn:Number($(kind+'Time').value),timeUnit:$(kind+'Unit').value,offset:kind==='bp'?Number($('bpOffset').value):0});
  state.ecg=parse('ecg');state.bp=parse('bp');state.peaks=detectRPeaks(state.ecg);state.manual.clear();
}
function run(keepSignals=false){try{
  if(!keepSignals&&!state.demo)readUploads();
  if(!state.ecg||!state.bp)throw Error('No recordings loaded.');
  const startTime=state.ecg.times[0],endTime=state.ecg.times.at(-1);
  let start,end;
  if($('windowMode').value==='last'){const minutes=Number($('windowMinutes').value);if(!(minutes>.0))throw Error('Enter a positive window length.');end=endTime;start=Math.max(startTime,end-minutes*60);}else{start=Number($('windowStart').value);end=Number($('windowEnd').value);}
  if(!(end>start)||start<startTime||end>endTime+.001)throw Error('Choose a valid window within the ECG recording.');
  if(end-start<30)throw Error('Choose at least a 30-second analysis window.');
  state.analysis=analyze(state.ecg,state.bp,start,end,settings(),state.manual,state.peaks);
  $('emptyReview').hidden=$('emptyResults').hidden=true;$('reviewContent').hidden=$('resultsContent').hidden=false;$('download').disabled=false;
  $('focus').min=String(start);$('focus').max=String(Math.max(start,end-1));$('focus').step='0.1';$('focus').value=String(start);
  render();notice(`${state.analysis.summary.accepted} accepted beats in ${((end-start)/60).toFixed(1)} minutes. Review flags and R peaks before using the results.`);
}catch(e){notice(e.message,true);}}
function rerun(){if(!state.analysis)return;try{const a=state.analysis;state.analysis=analyze(state.ecg,state.bp,a.windowStart,a.windowEnd,settings(),state.manual,state.peaks);render();}catch(e){notice(e.message,true);}}
function fmt(v,n=1){return Number.isFinite(v)?v.toFixed(n):'—';}
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const N='http://www.w3.org/2000/svg';
function svgEl(tag,attrs={}){const e=document.createElementNS(N,tag);for(const [k,v] of Object.entries(attrs))e.setAttribute(k,String(v));return e;}
function path(values,times,x0,x1,yMin,yMax,w=1000,h=220,pad=28,color='#15918b'){
  const range=yMax-yMin||1,first=lowerBound(times,x0),last=Math.min(times.length,lowerBound(times,x1)+1),step=Math.max(1,Math.floor((last-first)/1600));let d='';
  for(let i=first;i<last;i+=step){const x=pad+(times[i]-x0)/(x1-x0)*(w-pad*2),y=h-pad-(values[i]-yMin)/range*(h-pad*2);if(Number.isFinite(x)&&Number.isFinite(y))d+=(d?' L':'M')+x.toFixed(1)+' '+y.toFixed(1);}
  return svgEl('path',{d,fill:'none',stroke:color,'stroke-width':2,'stroke-linecap':'round','stroke-linejoin':'round'});
}
function lowerBound(a,x){let lo=0,hi=a.length;while(lo<hi){const m=(lo+hi)>>1;if(a[m]<x)lo=m+1;else hi=m;}return lo;}
function baseChart(svg,x0,x1,yMin,yMax,h){svg.replaceChildren();const p=28;for(let i=0;i<=4;i++){const y=p+i*(h-2*p)/4;svg.append(svgEl('line',{x1:p,y1:y,x2:1000-p,y2:y,stroke:'#e7efed','stroke-width':1}));const t=svgEl('text',{x:3,y:y+4});t.textContent=fmt(yMax-i*(yMax-yMin)/4,0);svg.append(t);}for(let i=0;i<=4;i++){const x=p+i*(1000-2*p)/4;const t=svgEl('text',{x:x-12,y:h-5});t.textContent=fmt(x0+i*(x1-x0)/4,0)+'s';svg.append(t);}}
function markers(svg,points,x0,x1,yMin,yMax,h,color,radius=4){for(const p of points){if(p.time<x0||p.time>x1||!Number.isFinite(p.value))continue;const x=28+(p.time-x0)/(x1-x0)*944,y=h-28-(p.value-yMin)/(yMax-yMin||1)*(h-56);svg.append(svgEl('circle',{cx:x,cy:y,r:radius,fill:p.color||color,stroke:'#fff','stroke-width':1.3}));}}
function focusPlot(){const a=state.analysis,span=Number($('viewSpan').value),center=Number($('focus').value),start=Math.max(a.windowStart,Math.min(a.windowEnd-span,center)),end=Math.min(a.windowEnd,start+span);$('focusLabel').textContent=fmt(start,1)+' s';
  const e=state.ecg,ecgSvg=$('ecgChart'),ei=lowerBound(e.times,start),ej=lowerBound(e.times,end),data=Array.from(e.values.slice(ei,ej));if(!data.length)return;let lo=Math.min(...data),hi=Math.max(...data),margin=(hi-lo)*.15||1;lo-=margin;hi+=margin;baseChart(ecgSvg,start,end,lo,hi,220);ecgSvg.append(path(e.values,e.times,start,end,lo,hi));const bad=new Set(a.beats.filter(b=>!b.accepted).map(b=>b.i));markers(ecgSvg,a.peaks.map((p,i)=>({time:p.time,value:e.values[p.index],color:bad.has(i)?'#df7065':'#249a84'})),start,end,lo,hi,220,'#239985',5);
  const b=state.bp,bpSvg=$('bpChart'),bi=lowerBound(b.times,start),bj=lowerBound(b.times,end),bd=Array.from(b.values.slice(bi,bj));if(!bd.length)return;lo=Math.min(...bd);hi=Math.max(...bd);margin=(hi-lo)*.12||1;lo-=margin;hi+=margin;baseChart(bpSvg,start,end,lo,hi,200);bpSvg.append(path(b.values,b.times,start,end,lo,hi,1000,200,28,'#7762aa'));const visible=a.beats.filter(x=>x.time>=start&&x.time<=end);markers(bpSvg,visible.map(x=>({time:x.sbpTime,value:x.sbp,color:x.accepted?'#7762aa':'#df7065'})),start,end,lo,hi,200,'#7762aa',4);markers(bpSvg,visible.map(x=>({time:x.dbpTime,value:x.dbp,color:x.accepted?'#229b92':'#df7065'})),start,end,lo,hi,200,'#229b92',3);
}
function beatPlot(){const a=state.analysis,svg=$('beatChart'),beats=a.beats,x0=state.ecg.times[0],x1=state.ecg.times.at(-1);let lo=Math.min(...beats.map(b=>b.dbp).filter(Number.isFinite)),hi=Math.max(...beats.map(b=>b.sbp).filter(Number.isFinite));if(!Number.isFinite(lo)||!Number.isFinite(hi))return;lo-=8;hi+=8;baseChart(svg,x0,x1,lo,hi,220);const xx=t=>28+(t-x0)/(x1-x0)*944;svg.insertBefore(svgEl('rect',{x:xx(a.windowStart),y:28,width:xx(a.windowEnd)-xx(a.windowStart),height:164,fill:'#f9ecd0',opacity:.42}),svg.firstChild);for(const [key,color] of [['sbp','#7968ad'],['dbp','#229b92']]){let d='';for(const b of beats){if(!b.accepted)continue;const x=xx(b.time),y=192-(b[key]-lo)/(hi-lo)*164;d+=(d?' L':'M')+x.toFixed(1)+' '+y.toFixed(1);}svg.append(svgEl('path',{d,fill:'none',stroke:color,'stroke-width':2.3}));}for(const b of beats)if(!b.accepted&&Number.isFinite(b.sbp)){const x=xx(b.time),y=192-(b.sbp-lo)/(hi-lo)*164;svg.append(svgEl('circle',{cx:x,cy:y,r:3.8,fill:'#df7065'}));}}
$('focus').addEventListener('input',focusPlot);$('viewSpan').addEventListener('change',focusPlot);
$('ecgChart').addEventListener('click',event=>{if(!state.analysis)return;const rect=event.currentTarget.getBoundingClientRect(),fraction=(event.clientX-rect.left)/rect.width;const a=state.analysis,span=Number($('viewSpan').value),center=Number($('focus').value),start=Math.max(a.windowStart,Math.min(a.windowEnd-span,center)),end=Math.min(a.windowEnd,start+span),time=start+Math.max(0,Math.min(1,(fraction*1000-28)/944))*(end-start);
  const nearest=state.peaks.reduce((best,p,i)=>!best||Math.abs(p.time-time)<Math.abs(best.p.time-time)?{p,i}:best,null);
  if(nearest&&Math.abs(nearest.p.time-time)<.10){state.peaks.splice(nearest.i,1);notice(`Removed R peak at ${fmt(nearest.p.time,2)} s.`);}else{const e=state.ecg,mid=lowerBound(e.times,time),radius=Math.round(e.fs*.065);let idx=mid,base=0;for(let j=Math.max(0,mid-radius);j<Math.min(e.values.length,mid+radius);j++){const x=Math.abs(e.values[j]);if(x>base){base=x;idx=j;}}state.peaks.push({index:idx,time:e.times[idx],score:base});state.peaks.sort((x,y)=>x.time-y.time);notice(`Added R peak at ${fmt(e.times[idx],2)} s.`);}state.manual.clear();rerun();});
function metric(label,value,unit='',digits=1){return `<div class="metric"><small>${esc(label)}</small><strong>${fmt(value,digits)}</strong><em>${esc(unit)}</em></div>`;}
function render(){const a=state.analysis,s=a.summary,rate=s.n?s.accepted/s.n:0;$('windowMeta').textContent=`${fmt(a.windowStart,1)}–${fmt(a.windowEnd,1)} s · ${s.n} beats · ${s.rejected} flagged`;
  focusPlot();beatPlot();const counts={};for(const b of a.beats)for(const f of b.flags)counts[f]=(counts[f]||0)+1;$('qcStrip').innerHTML=`<span class="chip">${s.accepted} accepted</span><span class="chip warn">${s.rejected} rejected</span>`+Object.entries(counts).map(([k,v])=>`<span class="chip warn">${esc(k)} · ${v}</span>`).join('');
  const tbody=$('beatRows');tbody.replaceChildren();a.beats.slice(0,120).forEach((b,i)=>{const tr=document.createElement('tr');if(!b.accepted)tr.className='rejected';tr.innerHTML=`<td>${i+1}</td><td>${fmt(b.time,2)} s</td><td>${fmt(b.rr,0)}</td><td>${fmt(b.sbp,1)}</td><td>${fmt(b.dbp,1)}</td><td>${fmt(b.map,1)}</td><td>${fmt(b.pp,1)}</td><td>${esc(b.flags.join('; ')||'Accepted')}</td><td><button type="button">${state.manual.has(i)?'Restore':'Reject'}</button></td>`;tr.querySelector('button').onclick=()=>{state.manual.has(i)?state.manual.delete(i):state.manual.add(i);rerun();};tbody.append(tr);});
  $('hrvMetrics').innerHTML=metric('Mean heart rate',s.hrv.meanHR,'bpm')+metric('Mean NN',s.hrv.meanNN,'ms')+metric('SDNN',s.hrv.sdnn,'ms')+metric('RMSSD',s.hrv.rmssd,'ms')+metric('pNN50',s.hrv.pnn50,'%')+metric('LF power',s.hrv.lf,'ms²')+metric('HF power',s.hrv.hf,'ms²')+metric('LF/HF',s.hrv.lfHf,'',2);
  $('bpMetrics').innerHTML=metric('Mean SBP',s.bp.sbp,'mmHg')+metric('Mean DBP',s.bp.dbp,'mmHg')+metric('Mean MAP',s.bp.map,'mmHg')+metric('Mean PP',s.bp.pp,'mmHg');
  $('brsMetrics').innerHTML=metric('SBP SD',s.bpv.sbpSD,'mmHg')+metric('SBP CV',s.bpv.sbpCV,'%')+metric('SBP ARV',s.bpv.sbpARV,'mmHg')+metric('DBP SD',s.bpv.dbpSD,'mmHg')+metric('MAP SD',s.bpv.mapSD,'mmHg')+metric('Sequence BRS',s.brs.meanSlope,'ms/mmHg')+metric('BRS sequences',s.brs.count,'',0)+metric('Up / down',s.brs.up,' / '+s.brs.down,0);
  const warnings=[];if(rate<.95)warnings.push(`${fmt((1-rate)*100,1)}% of beats flagged`);if(s.accepted<100)warnings.push('Fewer than 100 accepted beats');if(!Number.isFinite(s.brs.meanSlope))warnings.push('No qualifying BRS sequences');if(!Number.isFinite(s.hrv.lf))warnings.push('Spectral HRV withheld due to QC or window length');if(state.ecg.skipped||state.bp.skipped)warnings.push(`${state.ecg.skipped+state.bp.skipped} nonnumeric input lines skipped`);
  const banner=$('qualityBanner');banner.textContent=warnings.length?'Review before interpretation: '+warnings.join(' · '):'QC summary: sufficient accepted beats for all displayed calculations. Verify waveforms and alignment before reporting.';banner.classList.toggle('warn',!!warnings.length);
}
function csvCell(x){const s=String(x??'');return /[",\n]/.test(s)?'"'+s.replaceAll('"','""')+'"':s;}
$('download').addEventListener('click',()=>{const a=state.analysis;if(!a)return;const s=a.summary;const rows=[['Resting HRV & BRS Lab','browser-local analysis'],['window_start_s',a.windowStart],['window_end_s',a.windowEnd],['accepted_beats',s.accepted],['rejected_beats',s.rejected],...Object.entries(settings()).map(([k,v])=>[k,v]),[],['metric','value','unit'],['mean_HR',s.hrv.meanHR,'bpm'],['mean_NN',s.hrv.meanNN,'ms'],['SDNN',s.hrv.sdnn,'ms'],['RMSSD',s.hrv.rmssd,'ms'],['pNN50',s.hrv.pnn50,'%'],['LF',s.hrv.lf,'ms2'],['HF',s.hrv.hf,'ms2'],['LF_HF',s.hrv.lfHf,''],['mean_SBP',s.bp.sbp,'mmHg'],['mean_DBP',s.bp.dbp,'mmHg'],['mean_MAP',s.bp.map,'mmHg'],['mean_PP',s.bp.pp,'mmHg'],['SBP_SD',s.bpv.sbpSD,'mmHg'],['SBP_CV',s.bpv.sbpCV,'%'],['SBP_ARV',s.bpv.sbpARV,'mmHg'],['DBP_SD',s.bpv.dbpSD,'mmHg'],['MAP_SD',s.bpv.mapSD,'mmHg'],['sequence_BRS',s.brs.meanSlope,'ms/mmHg'],['BRS_sequences',s.brs.count,'count'],[],['beat','time_s','RR_ms','SBP_mmHg','DBP_mmHg','MAP_mmHg','PP_mmHg','accepted','QC_flags'],...a.beats.map((b,i)=>[i+1,b.time,b.rr,b.sbp,b.dbp,b.map,b.pp,b.accepted,b.flags.join('; ')])];const csv=rows.map(row=>row.map(csvCell).join(',')).join('\r\n');const blob=new Blob([csv],{type:'text/csv'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='hrv_brs_beat_review.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
